# Generated by Django 3.0.4 on 2020-10-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
