# Generated by Django 3.0.4 on 2020-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticketapi', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('files', models.FileField(blank=True, max_length=140, upload_to=None)),
            ],
        ),
    ]
